### PR TITLE
Fix build issues with recent Runelite changes

### PR DESCRIPTION
**Pull request by robmonte**
I think this is all that's needed to get the plugin running again after they made some recent changes.

### CODE REVIEW

**Comment by robmonte** [comment]
@adituv Can you also leave a comment here giving me permission to submit a PR on your behalf to the Runelite repo to update the plugin? (Or you can make that PR yourself, same to me either way)

**Comment by adituv** [comment]
@robmonte Full permission granted.  I don't play runescape and don't want to maintain this further so I'm happy for you or another to adopt it.

**Comment by robmonte** [comment]
> @robmonte Full permission granted. I don't play runescape and don't want to maintain this further so I'm happy for you or another to adopt it.

@adituv In that case, I can change the repo Runelite uses to my own fork so you no longer have to worry about pull requests. Would you prefer that?

**Comment by adituv** [comment]
That would probably be the best way forward.  If you are willing to adopt this plugin and become the maintainer, feel free.

**Comment by robmonte** [comment]
I'll do that then. Thanks for making this plugin for everyone, it's been super helpful!

**Pull request closed without merging**
